cloud.aws.stack.auto=false
ncp.accessKey=4581474929E89E2F5CA5
ncp.secretKey=5FF0B81F3281AF99C7E2388EBB06D2EC1D1A4F17
ncp.regionName=kr-standard
ncp.endPoint=https://kr.object.ncloudstorage.com
cloud.aws.region.static=ap-northeast-2